version: '3'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./templates:/templates
    networks:
      - main

  redis:
    image: redis:latest
    networks:
      - main

networks:
  main:
